# Linuc dotfiles — kitty
font_family      JetBrainsMono Nerd Font
font_size        11.5
window_padding_width 10
background_opacity 0.92
confirm_os_window_close 0

# tema Material You (reescrito pelo matugen -> ~/.config/kitty/colors.conf)
include colors.conf

cursor_shape beam
cursor_blink_interval 0.5
scrollback_lines 10000
enable_audio_bell no
shell zsh
shell_integration enabled

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+t new_tab
map ctrl+shift+w close_tab
