background {
    monitor =
    path = ~/.config/hypr/wallpapers/current.jpg
    blur_passes = 2
    blur_size = 6
    noise = 0.01
}

input-field {
    monitor =
    size = 280, 56
    outline_thickness = 2
    rounding = 28
    outer_color = rgba({{colors.primary.rgb}}ee)
    inner_color = rgba({{colors.surface.rgb}}cc)
    font_color = rgba({{colors.on_surface.rgb}}ff)
    placeholder_text = <i>Senha</i>
    fade_on_empty = true
    position = 0, -160
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    font_size = 72
    font_family = Roboto Flex
    color = rgba({{colors.on_surface.rgb}}ff)
    position = 0, 60
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A, %d de %B')"
    font_size = 18
    font_family = Roboto Flex
    color = rgba({{colors.primary.rgb}}ff)
    position = 0, -30
    halign = center
    valign = center
}
