# auto-gerado pelo matugen
foreground {{colors.on_surface.hex}}
background {{colors.surface.hex}}
color0  {{colors.surface.hex}}
color8  {{colors.surface_variant.hex}}
color1  {{colors.error.hex}}
color9  {{colors.error.hex}}
color2  {{colors.tertiary.hex}}
color10 {{colors.tertiary.hex}}
color3  {{colors.secondary.hex}}
color11 {{colors.secondary.hex}}
color4  {{colors.primary.hex}}
color12 {{colors.primary.hex}}
color5  {{colors.tertiary.hex}}
color13 {{colors.tertiary.hex}}
color6  {{colors.primary.hex}}
color14 {{colors.primary.hex}}
color7  {{colors.on_surface_variant.hex}}
color15 {{colors.on_surface.hex}}
